{
  "uid" : "e185b8185c28853",
  "name" : "test order db create backup",
  "fullName" : "tests_api.test_bd.TestBackup#test_order_db_create_backup",
  "historyId" : "bbc51bc9e59c2f7de52280f53d30e264",
  "time" : {
    "start" : 1755223212887,
    "stop" : 1755223212887,
    "duration" : 0
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: Incorrect status code: 502",
  "statusTrace" : "@pytest.fixture()\n    def get_token_backup_2():\n        \"\"\"\n        Method return:\\n\n        token: str\\n\n        body: dict\\n\n        uuid: str\n        \"\"\"\n        load_dotenv()\n        email = os.getenv('BACKUP2_MAIL')\n        old_password = os.getenv('BACKUP2_PASSWORD')\n        uuid = os.getenv('BACKUP2_UUID')\n        body = {\"email\": email, \"password\": old_password}\n        result = requests.post('https://dbend.areso.pro/login', json=body)\n>       Checking.check_status_code(result, 200)\n\nconftest.py:113: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresult = <Response [502]>, status_code = 200\n\n    @staticmethod\n    def check_status_code(result: requests.models.Response, status_code: int):\n        \"\"\"\n        Method check status code\n        :param result: Response\n        :param status_code:\n        \"\"\"\n        with allure.step(f'Assert status code: {status_code} == Response status code: {result.status_code}'):\n>           assert status_code == result.status_code, f'Incorrect status code: {result.status_code}'\nE           AssertionError: Incorrect status code: 502\n\ntests_api/utils/checking.py:16: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "get_token_backup_2",
    "time" : {
      "start" : 1755223212887,
      "stop" : 1755223213168,
      "duration" : 281
    },
    "status" : "failed",
    "statusMessage" : "AssertionError: Incorrect status code: 502\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Oblache/Oblache/conftest.py\", line 113, in get_token_backup_2\n    Checking.check_status_code(result, 200)\n  File \"/home/runner/work/Oblache/Oblache/tests_api/utils/checking.py\", line 16, in check_status_code\n    assert status_code == result.status_code, f'Incorrect status code: {result.status_code}'\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "steps" : [ {
      "name" : "Assert status code: 200 == Response status code: 502",
      "time" : {
        "start" : 1755223213167,
        "stop" : 1755223213167,
        "duration" : 0
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: Incorrect status code: 502\n",
      "statusTrace" : "  File \"/home/runner/work/Oblache/Oblache/tests_api/utils/checking.py\", line 16, in check_status_code\n    assert status_code == result.status_code, f'Incorrect status code: {result.status_code}'\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Test Backup"
  }, {
    "name" : "parentSuite",
    "value" : "tests_api"
  }, {
    "name" : "subSuite",
    "value" : "TestBackup"
  }, {
    "name" : "host",
    "value" : "pkrvmubgrv54qmi"
  }, {
    "name" : "thread",
    "value" : "2604-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests_api.test_bd"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 36,
        "broken" : 125,
        "skipped" : 0,
        "passed" : 96,
        "unknown" : 0,
        "total" : 257
      },
      "items" : [ {
        "uid" : "a4b3e5511d7a6769",
        "reportUrl" : "https://lambotik.github.io/Oblache/471//#testresult/a4b3e5511d7a6769",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f6d09f92e40>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1755136872037,
          "stop" : 1755136902447,
          "duration" : 30410
        }
      }, {
        "uid" : "748ff24db1615dd8",
        "reportUrl" : "https://lambotik.github.io/Oblache/470//#testresult/748ff24db1615dd8",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fae4d8d4680>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1755050408105,
          "stop" : 1755050438615,
          "duration" : 30510
        }
      }, {
        "uid" : "7add227251febfbc",
        "reportUrl" : "https://lambotik.github.io/Oblache/469//#testresult/7add227251febfbc",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fdb9f830800>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754963886983,
          "stop" : 1754963917392,
          "duration" : 30409
        }
      }, {
        "uid" : "c17b8b8ce2932321",
        "reportUrl" : "https://lambotik.github.io/Oblache/468//#testresult/c17b8b8ce2932321",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f95c332eba0>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754878208069,
          "stop" : 1754878238655,
          "duration" : 30586
        }
      }, {
        "uid" : "9edb6156da7a2d9b",
        "reportUrl" : "https://lambotik.github.io/Oblache/467//#testresult/9edb6156da7a2d9b",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 502",
        "time" : {
          "start" : 1754791991480,
          "stop" : 1754791991480,
          "duration" : 0
        }
      }, {
        "uid" : "2083d2c7ad05e948",
        "reportUrl" : "https://lambotik.github.io/Oblache/466//#testresult/2083d2c7ad05e948",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fc291be5ee0>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754704746746,
          "stop" : 1754704777198,
          "duration" : 30452
        }
      }, {
        "uid" : "770535b5434d5f5f",
        "reportUrl" : "https://lambotik.github.io/Oblache/465//#testresult/770535b5434d5f5f",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 502",
        "time" : {
          "start" : 1754618950041,
          "stop" : 1754618950041,
          "duration" : 0
        }
      }, {
        "uid" : "2b252731d11f8e2a",
        "reportUrl" : "https://lambotik.github.io/Oblache/464//#testresult/2b252731d11f8e2a",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f7b37a82810>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754532669558,
          "stop" : 1754532700137,
          "duration" : 30579
        }
      }, {
        "uid" : "ecf069bc025baf63",
        "reportUrl" : "https://lambotik.github.io/Oblache/463//#testresult/ecf069bc025baf63",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 502",
        "time" : {
          "start" : 1754446165573,
          "stop" : 1754446165573,
          "duration" : 0
        }
      }, {
        "uid" : "3646de2cf481cfc",
        "reportUrl" : "https://lambotik.github.io/Oblache/462//#testresult/3646de2cf481cfc",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fbcf819de50>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754359926994,
          "stop" : 1754359957386,
          "duration" : 30392
        }
      }, {
        "uid" : "d7298072d95e2fd8",
        "reportUrl" : "https://lambotik.github.io/Oblache/461//#testresult/d7298072d95e2fd8",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f6aeac130e0>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754274250904,
          "stop" : 1754274281318,
          "duration" : 30414
        }
      }, {
        "uid" : "d3d3d89f64cbbd07",
        "reportUrl" : "https://lambotik.github.io/Oblache/460//#testresult/d3d3d89f64cbbd07",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f323c23a7b0>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754187911657,
          "stop" : 1754187942294,
          "duration" : 30637
        }
      }, {
        "uid" : "7b50cf5918dca4cf",
        "reportUrl" : "https://lambotik.github.io/Oblache/459//#testresult/7b50cf5918dca4cf",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f4c509e0ce0>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754100247094,
          "stop" : 1754100277509,
          "duration" : 30415
        }
      }, {
        "uid" : "21d87b6a9cc8906",
        "reportUrl" : "https://lambotik.github.io/Oblache/458//#testresult/21d87b6a9cc8906",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f3468556600>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754015169903,
          "stop" : 1754015200326,
          "duration" : 30423
        }
      }, {
        "uid" : "eb8c083c5e8a1270",
        "reportUrl" : "https://lambotik.github.io/Oblache/457//#testresult/eb8c083c5e8a1270",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f8f1c3e2360>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1753927747733,
          "stop" : 1753927778227,
          "duration" : 30494
        }
      }, {
        "uid" : "45f286d179ff0310",
        "reportUrl" : "https://lambotik.github.io/Oblache/456//#testresult/45f286d179ff0310",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f3935461730>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1753841351058,
          "stop" : 1753841381511,
          "duration" : 30453
        }
      }, {
        "uid" : "af98fa105ebe1d64",
        "reportUrl" : "https://lambotik.github.io/Oblache/455//#testresult/af98fa105ebe1d64",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f54c42db320>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1753755907730,
          "stop" : 1753755938276,
          "duration" : 30546
        }
      }, {
        "uid" : "6e2d8d17e8326eb9",
        "reportUrl" : "https://lambotik.github.io/Oblache/454//#testresult/6e2d8d17e8326eb9",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fb1e3cdfc80>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1753668792345,
          "stop" : 1753668822890,
          "duration" : 30545
        }
      }, {
        "uid" : "c86bcc03b1f3ba95",
        "reportUrl" : "https://lambotik.github.io/Oblache/453//#testresult/c86bcc03b1f3ba95",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f3267d03e00>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1753582929250,
          "stop" : 1753582959880,
          "duration" : 30630
        }
      }, {
        "uid" : "7757247a783d410d",
        "reportUrl" : "https://lambotik.github.io/Oblache/452//#testresult/7757247a783d410d",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7ff050dfbd10>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1753495329803,
          "stop" : 1753495360223,
          "duration" : 30420
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "e185b8185c28853.json",
  "parameterValues" : [ ]
}